#!/usr/bin/env node
/**
 * Netlify build: inject the Railway web-app URL and the Android APK URL into the site.
 * - QV_WEB_APP_URL=https://your-app.up.railway.app
 * - QV_APK_URL (optional) — defaults to the APK the "Android APK" GitHub workflow publishes.
 *   The URL is only written when it actually answers, so the button never points at a 404.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webAppUrl = process.env.QV_WEB_APP_URL?.replace(/\/$/, "") ?? "";
const apkCandidate =
  process.env.QV_APK_URL ??
  "https://github.com/FelipeGazapina/questvault/releases/download/android-latest/questvault.apk";

async function reachable(url) {
  try {
    const res = await fetch(url, { method: "HEAD", redirect: "follow" });
    return res.ok;
  } catch {
    return false;
  }
}

const apkUrl = apkCandidate && (await reachable(apkCandidate)) ? apkCandidate : "";

const configJs = `// Generated by netlify-build.mjs — do not edit
window.QV_WEB_APP_URL = ${JSON.stringify(webAppUrl ? `${webAppUrl}/` : "/app/")};
window.QV_APK_URL = ${JSON.stringify(apkUrl)};
`;

writeFileSync(join(here, "..", "config.js"), configJs, "utf8");
console.log("Wrote config.js with QV_WEB_APP_URL =", webAppUrl || "(local /app/)");
console.log("QV_APK_URL =", apkUrl || `(not available yet: ${apkCandidate})`);

// Optional Railway proxy: /app/* on the marketing domain forwards to the web app.
if (webAppUrl) {
  const redirects = `# Auto-generated — web app hosted on Railway\n/app/*  ${webAppUrl}/:splat  302\n`;
  writeFileSync(join(here, "..", "_redirects"), redirects, "utf8");
  console.log("Wrote _redirects → Railway");
}
