#!/usr/bin/env node
/**
 * Netlify build: inject Railway web-app URL into marketing site.
 * Set in Netlify UI: QV_WEB_APP_URL=https://your-app.up.railway.app
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webAppUrl = process.env.QV_WEB_APP_URL?.replace(/\/$/, "") ?? "";

const configJs = `// Generated by netlify-build.mjs — do not edit
window.QV_WEB_APP_URL = ${JSON.stringify(webAppUrl ? `${webAppUrl}/` : "/app/")};
`;

writeFileSync(join(here, "config.js"), configJs, "utf8");
console.log("Wrote config.js with QV_WEB_APP_URL =", webAppUrl || "(local /app/)");

// Patch _redirects for optional Railway proxy (when URL set, marketing links go direct)
if (webAppUrl) {
  const redirects = `# Auto-generated — web app hosted on Railway\n/app/*  ${webAppUrl}/:splat  302\n`;
  writeFileSync(join(here, "_redirects"), redirects, "utf8");
  console.log("Wrote _redirects → Railway");
}
