pos=FindEmptySpace({width:1200,height:900,direction:"right",padding:80,nodeId:"lgL63"})
landing=Insert(document,{type:"frame",name:"Screen Landing Web",x:pos.x,y:pos.y,width:1200,height:900,layout:"vertical",padding:[48,64],gap:32,fill:"$night",clip:true,placeholder:true})
hero=Insert(landing,{type:"frame",name:"Landing Hero",layout:"horizontal",gap:48,width:"fill_container",alignItems:"center"})
heroCopy=Insert(hero,{type:"frame",name:"Hero Copy",layout:"vertical",gap:16,width:"fill_container"})
Insert(heroCopy,{type:"text",name:"Hero H1",fontFamily:"$font-head",fontSize:22,fill:"$white",textGrowth:"fixed-width",width:480,content:"Your life.\nYour quests.\nYour loot.",lineHeight:1.6})
Insert(heroCopy,{type:"text",name:"Hero Lead",fontFamily:"$font-body",fontSize:24,fill:"$fog",textGrowth:"fixed-width",width:440,content:"A pixel-art RPG for real life. Forge quests, level up, keep your streak."})
ctaRow=Insert(heroCopy,{type:"frame",name:"Hero CTAs",layout:"horizontal",gap:12})
Insert(ctaRow,{type:"ref",ref:"EOtGZ",name:"Download CTA",fill:"$leaf",descendants:{"o7eos":{content:"DOWNLOAD APP",fill:"#0c2a18"}}})
Insert(ctaRow,{type:"ref",ref:"EOtGZ",name:"How CTA",fill:"$navy",descendants:{"o7eos":{content:"HOW IT WORKS",fill:"$sky"}}})
heroPhone=Insert(hero,{type:"frame",name:"Hero Phone",layout:"vertical",width:340,fill:"$night",stroke:"$ink",strokeWidth:4,padding:14,gap:10})
Insert(heroPhone,{type:"ref",ref:"Ym0xu",name:"Landing HUD",width:"fill_container"})
Insert(heroPhone,{type:"ref",ref:"f31Xd",name:"Landing Card",width:"fill_container"})
steps=Insert(landing,{type:"frame",name:"Landing Steps",layout:"horizontal",gap:16,width:"fill_container"})
for(const [n,t,b] of [["01","FORGE POOL","Add dailies, side quests, bosses."],["02","EARN XP","Random hand each period."],["03","BUILD LOOT","Wishlist with pixel icons."]]){
s=Insert(steps,{type:"frame",name:"Step "+n,layout:"vertical",gap:8,padding:16,fill:"$navy",stroke:"$ink",strokeWidth:3,width:"fill_container"})
Insert(s,{type:"text",name:"Step Num "+n,fontFamily:"$font-head",fontSize:20,fill:"$deep",content:n})
Insert(s,{type:"text",name:"Step Title "+n,fontFamily:"$font-head",fontSize:10,fill:"$white",content:t})
Insert(s,{type:"text",name:"Step Body "+n,fontFamily:"$font-body",fontSize:20,fill:"$fog",textGrowth:"fixed-width",width:"fill_container",content:b})
}
dl=Insert(landing,{type:"frame",name:"Landing Download",layout:"vertical",gap:12,padding:20,fill:"$panel-dark",stroke:"$ink",strokeWidth:3,width:"fill_container"})
Insert(dl,{type:"text",name:"DL Title",fontFamily:"$font-head",fontSize:14,fill:"$white",content:"Play now from the web"})
Insert(dl,{type:"text",name:"DL Lead",fontFamily:"$font-body",fontSize:22,fill:"$fog",textGrowth:"fixed-width",width:720,content:"Direct APK while App Store and Google Play are pending approval."})
Insert(dl,{type:"ref",ref:"EOtGZ",name:"APK Button",width:320,fill:"$leaf",descendants:{"o7eos":{content:"DOWNLOAD ANDROID",fill:"#0c2a18"}}})
future=Insert(landing,{type:"frame",name:"Landing Future",layout:"vertical",gap:10,padding:24,fill:"$navy",stroke:"$ember",strokeWidth:3,width:"fill_container",alignItems:"center"})
Insert(future,{type:"text",name:"Future Title",fontFamily:"$font-head",fontSize:12,fill:"$white",content:"The adventure has just begun"})
Insert(future,{type:"text",name:"Future Body",fontFamily:"$font-body",fontSize:22,fill:"$fog",textGrowth:"fixed-width",width:560,textAlign:"center",content:"Big ideas are forging ahead — stay tuned for what's next."})
Insert(future,{type:"text",name:"Future Hint",fontFamily:"$font-head",fontSize:8,fill:"$ember",content:"STAY TUNED · UPDATES INCOMING"})
Update(landing,{placeholder:false})
