pos=FindEmptySpace({width:390,height:844,direction:"right",padding:80,nodeId:"gZZg5"})
s2=Insert(document,{type:"frame",name:"Screen Vault",x:pos.x,y:pos.y,width:390,height:844,layout:"vertical",padding:16,gap:12,fill:"$night",clip:true,placeholder:true})
Insert(s2,{type:"ref",ref:"Ym0xu",name:"Vault HUD",width:"fill_container"})
s2title=Insert(s2,{type:"frame",name:"Vault Title Row",layout:"horizontal",justifyContent:"center",width:"fill_container",padding:[8,0,0,0]})
Insert(s2title,{type:"text",name:"Vault Title",fontFamily:"$font-head",fontSize:13,fill:"$white",content:"THE VAULT"})
s2display=Insert(s2,{type:"frame",name:"Vault Display",layout:"vertical",alignItems:"center",gap:8,width:"fill_container",padding:[10,0]})
Insert(s2display,{type:"ref",ref:"B9cnP",name:"Vault Chest"})
Insert(s2display,{type:"text",name:"Sealed Label",fontFamily:"$font-head",fontSize:9,fill:"$fog",content:"SEALED — UNLOCK BY QUESTING"})
Insert(s2display,{type:"text",name:"Sealed Balance",fontFamily:"$font-head",fontSize:20,fill:"$gold",content:"R$ 127,00"})
Insert(s2display,{type:"frame",name:"Balance Gap",width:10,height:6})
Insert(s2display,{type:"text",name:"Pouch Label",fontFamily:"$font-head",fontSize:9,fill:"$fog",content:"GOLD POUCH — READY TO SPEND"})
Insert(s2display,{type:"text",name:"Pouch Balance",fontFamily:"$font-head",fontSize:14,fill:"$ice",content:"R$ 23,00"})
Insert(s2,{type:"ref",ref:"EOtGZ",name:"Stash Button",width:"fill_container",descendants:{"o7eos":{content:"+ STASH GOLD (PIX)"}}})
s2ledger=Insert(s2,{type:"frame",name:"Ledger Panel",layout:"vertical",gap:9,padding:[10,12],fill:"$panel-dark",stroke:"$ink",strokeWidth:3,width:"fill_container"})
Insert(s2ledger,{type:"text",name:"Ledger Header",fontFamily:"$font-head",fontSize:8,fill:"$slate",content:"LEDGER — EVERY COIN, TRACEABLE"})
Insert(s2ledger,{type:"ref",ref:"fzmDJ",name:"Ledger 1",width:"fill_container",descendants:{"u2sI5":{content:"Quest: Ran 2 km (Strava)"},"imTVU":{content:"R$ 2,00 unlocked",fill:"$gold"}}})
Insert(s2ledger,{type:"ref",ref:"fzmDJ",name:"Ledger 2",width:"fill_container",descendants:{"u2sI5":{content:"Level 12 bonus"},"imTVU":{content:"R$ 1,27 unlocked",fill:"$gold"}}})
Insert(s2ledger,{type:"ref",ref:"fzmDJ",name:"Ledger 3",width:"fill_container",descendants:{"u2sI5":{content:"Pix deposit"},"imTVU":{content:"+ R$ 50,00",fill:"$mint"}}})
Insert(s2ledger,{type:"ref",ref:"fzmDJ",name:"Ledger 4",width:"fill_container",descendants:{"u2sI5":{content:"Loot claimed: Pizza night"},"imTVU":{content:"− R$ 21,90",fill:"$ember"}}})
Insert(s2,{type:"text",name:"Escape Note",fontFamily:"$font-body",fontSize:17,fill:"$slate",textGrowth:"fixed-width",width:"fill_container",textAlign:"center",content:"Need your gold back? Leave the dungeon — always 100%, always free."})
Insert(s2,{type:"frame",name:"Vault Spacer",width:"fill_container",height:"fill_container"})
Insert(s2,{type:"ref",ref:"f31Xd",name:"Vault Nav",width:"fill_container",descendants:{"ca2B5":{fill:"$slate"},"NLY0t":{fill:"$slate"},"Rvxzr":{fill:"$gold"},"L9ixe":{fill:"$gold"}}})
Update(s2,{placeholder:false})
