pos=FindEmptySpace({width:390,height:844,direction:"right",padding:80,nodeId:"zdMWM"})
s5=Insert(document,{type:"frame",name:"Screen Redeem Confirm",x:pos.x,y:pos.y,width:390,height:844,layout:"vertical",justifyContent:"center",alignItems:"center",padding:16,fill:"#0d0e18",clip:true,placeholder:true})
modal=Insert(s5,{type:"frame",name:"Confirm Modal",layout:"vertical",gap:12,padding:18,fill:"$navy",stroke:"$ink",strokeWidth:4,width:340,effect:{type:"shadow",shadowType:"outer",offset:{x:6,y:6},blur:0,color:"#000000aa"}})
mh=Insert(modal,{type:"frame",name:"Modal Header Row",layout:"horizontal",justifyContent:"center",width:"fill_container"})
Insert(mh,{type:"text",name:"Modal Header",fontFamily:"$font-head",fontSize:12,fill:"$gold",content:"CLAIM LOOT?"})
Insert(modal,{type:"text",name:"Modal Item",fontFamily:"$font-body",fontSize:22,fill:"$white",content:"Pizza night (iFood)"})
amounts=Insert(modal,{type:"frame",name:"Amount Panel",layout:"vertical",gap:8,padding:12,fill:"$panel-dark",stroke:"$ink",strokeWidth:2,width:"fill_container"})
ar1=Insert(amounts,{type:"frame",name:"Amount Row",layout:"horizontal",justifyContent:"space_between",alignItems:"center",width:"fill_container"})
Insert(ar1,{type:"text",name:"Amount Label",fontFamily:"$font-money",fontSize:13,fill:"$fog",content:"Amount"})
Insert(ar1,{type:"text",name:"Amount Value",fontFamily:"$font-money",fontSize:17,fontWeight:"600",fill:"$white",content:"R$ 21,90"})
ar2=Insert(amounts,{type:"frame",name:"After Row",layout:"horizontal",justifyContent:"space_between",alignItems:"center",width:"fill_container"})
Insert(ar2,{type:"text",name:"After Label",fontFamily:"$font-money",fontSize:13,fill:"$fog",content:"Gold pouch after"})
Insert(ar2,{type:"text",name:"After Value",fontFamily:"$font-money",fontSize:14,fontWeight:"600",fill:"$fog",content:"R$ 1,10"})
Insert(modal,{type:"text",name:"Modal Note",fontFamily:"$font-body",fontSize:17,fill:"$fog",textGrowth:"fixed-width",width:"fill_container",content:"Paid with gold you unlocked by questing. iFood opens to complete your order."})
Insert(modal,{type:"ref",ref:"EOtGZ",name:"Confirm Button",width:"fill_container",fill:"$gold",descendants:{"o7eos":{content:"CONFIRM",fill:"#4a3208"}}})
cancel=Insert(modal,{type:"frame",name:"Cancel Button",layout:"horizontal",justifyContent:"center",alignItems:"center",padding:[10,16],stroke:"$ink",strokeWidth:3,width:"fill_container"})
Insert(cancel,{type:"text",name:"Cancel Label",fontFamily:"$font-head",fontSize:9,fill:"$slate",content:"CANCEL"})
Update(s5,{placeholder:false})

